### ISSUE TITLE
Продолжение

### ISSUE THREAD

**Issue by KorolevSoftware** [Drawell/TellMeSomething#1]
Я прошёл демоверсию и уверен вам стоит выпустить продолжение!
В 1 Акте чувствуется накал эмоций! но что дальше? Можно ли надавить на челика и отжать 15 рублей? как это повлияет на сюжет и концовку игры? Возможно вам стоить завести Потрион и там на донатах продолжить развитие игры.

**Comment by Drawell** [comment]
Продолжение, конечно же, будет! Имеется много идей для этой и других сюжетных линий. В настоящее время разрабатывается инструмент для создания сюжетов, но он еще не готов и поэтому разработка игры несколько задерживается. Но будьте уверены, что продолжение следует!
